# Custom Attack Configuration
operation: attack
attack_type: custom

# Transformation
transformation:
  module: textattack.transformations
  name: WordSwapEmbedding
  params:
    max_candidates: 15
    # embedding is automatically initialized with default

# Constraints
constraints:
  - module: textattack.constraints.semantics
    name: WordEmbeddingDistance
    params:
      min_cos_sim: 0.7
      
  - module: textattack.constraints.semantics.sentence_encoders.universal_sentence_encoder
    name: UniversalSentenceEncoder
    params:
      threshold: 0.8
      
  - module: textattack.constraints.overlap
    name: MaxWordsPerturbed
    params:
      max_percent: 0.2

# Pre-transformation constraints
pre_transformation_constraints:
  - module: textattack.constraints.pre_transformation
    name: StopwordModification
  
  - module: textattack.constraints.pre_transformation
    name: RepeatModification

# Model configuration
model:
  module: textattack.models.wrappers
  name: HuggingFaceModelWrapper
  params:
    model_name: distilbert-base-uncased-finetuned-sst-2-english

# Goal function
goal_function:
  module: textattack.goal_functions
  name: UntargetedClassification
  params:
    model_wrapper:
      _model_wrapper_injected_by_provider: true

# Search method
search_method:
  module: textattack.search_methods
  name: GreedyWordSwapWIR
  params:
    wir_method: gradient

# Dataset configuration
dataset:
  standard:
    module: textattack.datasets
    name: HuggingFaceDataset
    params:
      name_or_dataset: glue
      subset: sst2
      split: validation
      dataset_columns: [
        ["sentence"],
        "label"
      ]

# Attack parameters
attack_params:
  num_examples: 10
  shuffle: true

# Logging configuration
loggers:
  - module: textattack.loggers
    name: CSVLogger
    params:
      filename: results/textattack/wordswap_results.csv